package com.gaoxy.lifeinusa.entities;
// Generated 2015-9-1 22:37:47 by Hibernate Tools 3.4.0.CR1

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * PubAuthorities generated by hbm2java
 */
@Entity
@Table(name = "pub_authorities")
public class PubAuthorities implements java.io.Serializable {

	private String authorityId;
	private String authorityName;
	private String authorityDesc;
	private int enabled;
	private int issys;
	private Set<PubRolesAuthorities> pubRolesAuthoritieses = new HashSet<PubRolesAuthorities>(0);
	private Set<PubAuthoritiesResources> pubAuthoritiesResourceses = new HashSet<PubAuthoritiesResources>(0);

	public PubAuthorities() {
	}

	public PubAuthorities(String authorityId, String authorityName, int enabled, int issys) {
		this.authorityId = authorityId;
		this.authorityName = authorityName;
		this.enabled = enabled;
		this.issys = issys;
	}

	public PubAuthorities(String authorityId, String authorityName, String authorityDesc, int enabled, int issys,
			Set<PubRolesAuthorities> pubRolesAuthoritieses, Set<PubAuthoritiesResources> pubAuthoritiesResourceses) {
		this.authorityId = authorityId;
		this.authorityName = authorityName;
		this.authorityDesc = authorityDesc;
		this.enabled = enabled;
		this.issys = issys;
		this.pubRolesAuthoritieses = pubRolesAuthoritieses;
		this.pubAuthoritiesResourceses = pubAuthoritiesResourceses;
	}

	@Id

	@Column(name = "authority_id", unique = true, nullable = false, length = 32)
	public String getAuthorityId() {
		return this.authorityId;
	}

	public void setAuthorityId(String authorityId) {
		this.authorityId = authorityId;
	}

	@Column(name = "authority_name", nullable = false, length = 40)
	public String getAuthorityName() {
		return this.authorityName;
	}

	public void setAuthorityName(String authorityName) {
		this.authorityName = authorityName;
	}

	@Column(name = "authority_desc", length = 100)
	public String getAuthorityDesc() {
		return this.authorityDesc;
	}

	public void setAuthorityDesc(String authorityDesc) {
		this.authorityDesc = authorityDesc;
	}

	@Column(name = "enabled", nullable = false)
	public int getEnabled() {
		return this.enabled;
	}

	public void setEnabled(int enabled) {
		this.enabled = enabled;
	}

	@Column(name = "issys", nullable = false)
	public int getIssys() {
		return this.issys;
	}

	public void setIssys(int issys) {
		this.issys = issys;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "pubAuthorities")
	public Set<PubRolesAuthorities> getPubRolesAuthoritieses() {
		return this.pubRolesAuthoritieses;
	}

	public void setPubRolesAuthoritieses(Set<PubRolesAuthorities> pubRolesAuthoritieses) {
		this.pubRolesAuthoritieses = pubRolesAuthoritieses;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "pubAuthorities")
	public Set<PubAuthoritiesResources> getPubAuthoritiesResourceses() {
		return this.pubAuthoritiesResourceses;
	}

	public void setPubAuthoritiesResourceses(Set<PubAuthoritiesResources> pubAuthoritiesResourceses) {
		this.pubAuthoritiesResourceses = pubAuthoritiesResourceses;
	}

}
