package com.gaoxy.lifeinusa.entities;
// Generated 2015-9-1 22:37:47 by Hibernate Tools 3.4.0.CR1

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * PubRoles generated by hbm2java
 */
@Entity
@Table(name = "pub_roles")
public class PubRoles implements java.io.Serializable {

	private String roleId;
	private String roleName;
	private String roleDesc;
	private int enabled;
	private int issys;
	private Set<PubUsersRoles> pubUsersRoleses = new HashSet<PubUsersRoles>(0);
	private Set<PubRolesAuthorities> pubRolesAuthoritieses = new HashSet<PubRolesAuthorities>(0);

	public PubRoles() {
	}

	public PubRoles(String roleId, String roleName, int enabled, int issys) {
		this.roleId = roleId;
		this.roleName = roleName;
		this.enabled = enabled;
		this.issys = issys;
	}

	public PubRoles(String roleId, String roleName, String roleDesc, int enabled, int issys,
			Set<PubUsersRoles> pubUsersRoleses, Set<PubRolesAuthorities> pubRolesAuthoritieses) {
		this.roleId = roleId;
		this.roleName = roleName;
		this.roleDesc = roleDesc;
		this.enabled = enabled;
		this.issys = issys;
		this.pubUsersRoleses = pubUsersRoleses;
		this.pubRolesAuthoritieses = pubRolesAuthoritieses;
	}

	@Id

	@Column(name = "role_id", unique = true, nullable = false, length = 32)
	public String getRoleId() {
		return this.roleId;
	}

	public void setRoleId(String roleId) {
		this.roleId = roleId;
	}

	@Column(name = "role_name", nullable = false, length = 100)
	public String getRoleName() {
		return this.roleName;
	}

	public void setRoleName(String roleName) {
		this.roleName = roleName;
	}

	@Column(name = "role_desc", length = 100)
	public String getRoleDesc() {
		return this.roleDesc;
	}

	public void setRoleDesc(String roleDesc) {
		this.roleDesc = roleDesc;
	}

	@Column(name = "enabled", nullable = false)
	public int getEnabled() {
		return this.enabled;
	}

	public void setEnabled(int enabled) {
		this.enabled = enabled;
	}

	@Column(name = "issys", nullable = false)
	public int getIssys() {
		return this.issys;
	}

	public void setIssys(int issys) {
		this.issys = issys;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "pubRoles")
	public Set<PubUsersRoles> getPubUsersRoleses() {
		return this.pubUsersRoleses;
	}

	public void setPubUsersRoleses(Set<PubUsersRoles> pubUsersRoleses) {
		this.pubUsersRoleses = pubUsersRoleses;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "pubRoles")
	public Set<PubRolesAuthorities> getPubRolesAuthoritieses() {
		return this.pubRolesAuthoritieses;
	}

	public void setPubRolesAuthoritieses(Set<PubRolesAuthorities> pubRolesAuthoritieses) {
		this.pubRolesAuthoritieses = pubRolesAuthoritieses;
	}

}
