package com.gaoxy.lifeinusa.entities;
// Generated 2015-9-1 22:37:47 by Hibernate Tools 3.4.0.CR1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * PubRolesAuthorities generated by hbm2java
 */
@Entity
@Table(name = "pub_roles_authorities")
public class PubRolesAuthorities implements java.io.Serializable {

	private String id;
	private PubRoles pubRoles;
	private PubAuthorities pubAuthorities;

	public PubRolesAuthorities() {
	}

	public PubRolesAuthorities(String id, PubRoles pubRoles, PubAuthorities pubAuthorities) {
		this.id = id;
		this.pubRoles = pubRoles;
		this.pubAuthorities = pubAuthorities;
	}

	@Id

	@Column(name = "id", unique = true, nullable = false, length = 32)
	public String getId() {
		return this.id;
	}

	public void setId(String id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "role_id", nullable = false)
	public PubRoles getPubRoles() {
		return this.pubRoles;
	}

	public void setPubRoles(PubRoles pubRoles) {
		this.pubRoles = pubRoles;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "authority_id", nullable = false)
	public PubAuthorities getPubAuthorities() {
		return this.pubAuthorities;
	}

	public void setPubAuthorities(PubAuthorities pubAuthorities) {
		this.pubAuthorities = pubAuthorities;
	}

}
