package com.gaoxy.lifeinusa.entities;
// Generated 2015-9-1 22:37:47 by Hibernate Tools 3.4.0.CR1

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * PubResources generated by hbm2java
 */
@Entity
@Table(name = "pub_resources")
public class PubResources implements java.io.Serializable {

	private String resourceId;
	private String resourceName;
	private String resourceType;
	private int priority;
	private String resourceString;
	private String resourceDesc;
	private int enabled;
	private int issys;
	private Set<PubAuthoritiesResources> pubAuthoritiesResourceses = new HashSet<PubAuthoritiesResources>(0);

	public PubResources() {
	}

	public PubResources(String resourceId, String resourceName, String resourceType, int priority,
			String resourceString, int enabled, int issys) {
		this.resourceId = resourceId;
		this.resourceName = resourceName;
		this.resourceType = resourceType;
		this.priority = priority;
		this.resourceString = resourceString;
		this.enabled = enabled;
		this.issys = issys;
	}

	public PubResources(String resourceId, String resourceName, String resourceType, int priority,
			String resourceString, String resourceDesc, int enabled, int issys,
			Set<PubAuthoritiesResources> pubAuthoritiesResourceses) {
		this.resourceId = resourceId;
		this.resourceName = resourceName;
		this.resourceType = resourceType;
		this.priority = priority;
		this.resourceString = resourceString;
		this.resourceDesc = resourceDesc;
		this.enabled = enabled;
		this.issys = issys;
		this.pubAuthoritiesResourceses = pubAuthoritiesResourceses;
	}

	@Id

	@Column(name = "resource_id", unique = true, nullable = false, length = 32)
	public String getResourceId() {
		return this.resourceId;
	}

	public void setResourceId(String resourceId) {
		this.resourceId = resourceId;
	}

	@Column(name = "resource_name", nullable = false, length = 100)
	public String getResourceName() {
		return this.resourceName;
	}

	public void setResourceName(String resourceName) {
		this.resourceName = resourceName;
	}

	@Column(name = "resource_type", nullable = false, length = 40)
	public String getResourceType() {
		return this.resourceType;
	}

	public void setResourceType(String resourceType) {
		this.resourceType = resourceType;
	}

	@Column(name = "priority", nullable = false)
	public int getPriority() {
		return this.priority;
	}

	public void setPriority(int priority) {
		this.priority = priority;
	}

	@Column(name = "resource_string", nullable = false, length = 200)
	public String getResourceString() {
		return this.resourceString;
	}

	public void setResourceString(String resourceString) {
		this.resourceString = resourceString;
	}

	@Column(name = "resource_desc", length = 100)
	public String getResourceDesc() {
		return this.resourceDesc;
	}

	public void setResourceDesc(String resourceDesc) {
		this.resourceDesc = resourceDesc;
	}

	@Column(name = "enabled", nullable = false)
	public int getEnabled() {
		return this.enabled;
	}

	public void setEnabled(int enabled) {
		this.enabled = enabled;
	}

	@Column(name = "issys", nullable = false)
	public int getIssys() {
		return this.issys;
	}

	public void setIssys(int issys) {
		this.issys = issys;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "pubResources")
	public Set<PubAuthoritiesResources> getPubAuthoritiesResourceses() {
		return this.pubAuthoritiesResourceses;
	}

	public void setPubAuthoritiesResourceses(Set<PubAuthoritiesResources> pubAuthoritiesResourceses) {
		this.pubAuthoritiesResourceses = pubAuthoritiesResourceses;
	}

}
