package com.gaoxy.lifeinusa.entities;
// Generated 2015-9-1 22:37:47 by Hibernate Tools 3.4.0.CR1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * TSecurityResc generated by hbm2java
 */
@Entity
@Table(name = "t_security_resc")
public class TSecurityResc implements java.io.Serializable {

	private long id;
	private String name;
	private String resType;
	private String resString;
	private Integer priority;
	private String descn;

	public TSecurityResc() {
	}

	public TSecurityResc(long id) {
		this.id = id;
	}

	public TSecurityResc(long id, String name, String resType, String resString, Integer priority, String descn) {
		this.id = id;
		this.name = name;
		this.resType = resType;
		this.resString = resString;
		this.priority = priority;
		this.descn = descn;
	}

	@Id

	@Column(name = "id", unique = true, nullable = false)
	public long getId() {
		return this.id;
	}

	public void setId(long id) {
		this.id = id;
	}

	@Column(name = "name", length = 50)
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	@Column(name = "res_type", length = 50)
	public String getResType() {
		return this.resType;
	}

	public void setResType(String resType) {
		this.resType = resType;
	}

	@Column(name = "res_string", length = 200)
	public String getResString() {
		return this.resString;
	}

	public void setResString(String resString) {
		this.resString = resString;
	}

	@Column(name = "priority")
	public Integer getPriority() {
		return this.priority;
	}

	public void setPriority(Integer priority) {
		this.priority = priority;
	}

	@Column(name = "descn", length = 200)
	public String getDescn() {
		return this.descn;
	}

	public void setDescn(String descn) {
		this.descn = descn;
	}

}
