package com.gaoxy.lifeinusa.entities;
// Generated 2015-9-1 22:37:47 by Hibernate Tools 3.4.0.CR1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * TSecurityUser generated by hbm2java
 */
@Entity
@Table(name = "t_security_user")
public class TSecurityUser implements java.io.Serializable {

	private String username;
	private String password;
	private Integer status;
	private String descn;

	public TSecurityUser() {
	}

	public TSecurityUser(String username, String password) {
		this.username = username;
		this.password = password;
	}

	public TSecurityUser(String username, String password, Integer status, String descn) {
		this.username = username;
		this.password = password;
		this.status = status;
		this.descn = descn;
	}

	@Id

	@Column(name = "username", unique = true, nullable = false, length = 50)
	public String getUsername() {
		return this.username;
	}

	public void setUsername(String username) {
		this.username = username;
	}

	@Column(name = "password", nullable = false, length = 50)
	public String getPassword() {
		return this.password;
	}

	public void setPassword(String password) {
		this.password = password;
	}

	@Column(name = "status")
	public Integer getStatus() {
		return this.status;
	}

	public void setStatus(Integer status) {
		this.status = status;
	}

	@Column(name = "descn", length = 200)
	public String getDescn() {
		return this.descn;
	}

	public void setDescn(String descn) {
		this.descn = descn;
	}

}
