package com.gaoxy.lifeinusa.entities;
// Generated 2015-9-1 22:37:47 by Hibernate Tools 3.4.0.CR1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * TSecurityRescRole generated by hbm2java
 */
@Entity
@Table(name = "t_security_resc_role")
public class TSecurityRescRole implements java.io.Serializable {

	private String id;
	private String rescId;
	private String roleId;

	public TSecurityRescRole() {
	}

	public TSecurityRescRole(String id) {
		this.id = id;
	}

	public TSecurityRescRole(String id, String rescId, String roleId) {
		this.id = id;
		this.rescId = rescId;
		this.roleId = roleId;
	}

	@Id

	@Column(name = "id", unique = true, nullable = false, length = 45)
	public String getId() {
		return this.id;
	}

	public void setId(String id) {
		this.id = id;
	}

	@Column(name = "resc_id", length = 50)
	public String getRescId() {
		return this.rescId;
	}

	public void setRescId(String rescId) {
		this.rescId = rescId;
	}

	@Column(name = "role_id", length = 50)
	public String getRoleId() {
		return this.roleId;
	}

	public void setRoleId(String roleId) {
		this.roleId = roleId;
	}

}
