package com.gaoxy.lifeinusa.entities;
// Generated 2015-9-1 22:37:47 by Hibernate Tools 3.4.0.CR1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * TSecurityRole generated by hbm2java
 */
@Entity
@Table(name = "t_security_role")
public class TSecurityRole implements java.io.Serializable {

	private String name;
	private String descn;
	private String id;

	public TSecurityRole() {
	}

	public TSecurityRole(String name, String descn) {
		this.name = name;
		this.descn = descn;
	}

	public TSecurityRole(String name, String descn, String id) {
		this.name = name;
		this.descn = descn;
		this.id = id;
	}

	@Id

	@Column(name = "name", unique = true, nullable = false, length = 50)
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	@Column(name = "descn", nullable = false, length = 200)
	public String getDescn() {
		return this.descn;
	}

	public void setDescn(String descn) {
		this.descn = descn;
	}

	@Column(name = "id", length = 45)
	public String getId() {
		return this.id;
	}

	public void setId(String id) {
		this.id = id;
	}

}
