package com.gaoxy.lifeinusa.entities;
// Generated 2015-9-1 22:37:47 by Hibernate Tools 3.4.0.CR1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * TSecurityUserRole generated by hbm2java
 */
@Entity
@Table(name = "t_security_user_role")
public class TSecurityUserRole implements java.io.Serializable {

	private String username;
	private String roleId;

	public TSecurityUserRole() {
	}

	public TSecurityUserRole(String username, String roleId) {
		this.username = username;
		this.roleId = roleId;
	}

	@Id

	@Column(name = "username", unique = true, nullable = false, length = 50)
	public String getUsername() {
		return this.username;
	}

	public void setUsername(String username) {
		this.username = username;
	}

	@Column(name = "role_id", nullable = false, length = 50)
	public String getRoleId() {
		return this.roleId;
	}

	public void setRoleId(String roleId) {
		this.roleId = roleId;
	}

}
