package com.gaoxy.lifeinusa.entities;
// Generated 2015-7-17 13:29:41 by Hibernate Tools 4.0.0

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Tusers generated by hbm2java
 */
@Entity
@Table(name = "Tusers", catalog = "lifeinusaDB")
public class Tusers implements java.io.Serializable {


	private String id;
	private String username;
	private String firstName;
	private Character middleInitial;
	private String lastName;
	private String email;
	private String officePhone;
	private String mobilePhone;
	private Integer accountStatusCode;
	private Integer userGroupId;
	private Integer securityContextId;
	private String userDescr;
	private Integer lastUpdateUser;
	private Date lastUpdateDate;
	private Integer lastWorkspaceId;
	private Integer lastProjectId;
	private String webmailUrl;
	private Integer customerId;
	private Long membershipType;
	private String mydocumentsPath;
	private String myphotosPath;
	private String mylinksPath;
	private String mymusicPath;
	private String myvideosPath;
	private String emailServer;
	private String emailUsername;
	private String emailPassword;
	private Integer emailAcctType;
	private Integer emailPortOutbound;
	private Integer emailPortInbound;
	private String password;
	private String homepage;
	private String activeStatus;
	private String password2;
	private String pictureFilepath;
	private Boolean termsAndConditionsFlag;
	private String userCompanyName;
	private String userAddress;
	private String userSuite;
	private String userCity;
	private String userState;
	private String userCountry;
	private String userPostalCode;
	private String favorites;
	private String emailAccounts;
	private String socialMediaAccounts;
	private Date createDate;
	private Integer createUser;
	private String apiKey;
	private String apiSecret;
	private String version;
	private String cloudName;

	public Tusers() {
	}

	public Tusers(String id, String username) {
		this.id = id;
		this.username = username;
	}

	public Tusers(String id, String username, String firstName, Character middleInitial, String lastName, String email,
			String officePhone, String mobilePhone, Integer accountStatusCode, Integer userGroupId,
			Integer securityContextId, String userDescr, Integer lastUpdateUser, Date lastUpdateDate,
			Integer lastWorkspaceId, Integer lastProjectId, String webmailUrl, Integer customerId, Long membershipType,
			String mydocumentsPath, String myphotosPath, String mylinksPath, String mymusicPath, String myvideosPath,
			String emailServer, String emailUsername, String emailPassword, Integer emailAcctType,
			Integer emailPortOutbound, Integer emailPortInbound, String password, String homepage, String activeStatus,
			String password2, String pictureFilepath, Boolean termsAndConditionsFlag, String userCompanyName,
			String userAddress, String userSuite, String userCity, String userState, String userCountry,
			String userPostalCode, String favorites, String emailAccounts, String socialMediaAccounts, Date createDate,
			Integer createUser, String apiKey, String apiSecret, String version, String cloudName) {
		this.id = id;
		this.username = username;
		this.firstName = firstName;
		this.middleInitial = middleInitial;
		this.lastName = lastName;
		this.email = email;
		this.officePhone = officePhone;
		this.mobilePhone = mobilePhone;
		this.accountStatusCode = accountStatusCode;
		this.userGroupId = userGroupId;
		this.securityContextId = securityContextId;
		this.userDescr = userDescr;
		this.lastUpdateUser = lastUpdateUser;
		this.lastUpdateDate = lastUpdateDate;
		this.lastWorkspaceId = lastWorkspaceId;
		this.lastProjectId = lastProjectId;
		this.webmailUrl = webmailUrl;
		this.customerId = customerId;
		this.membershipType = membershipType;
		this.mydocumentsPath = mydocumentsPath;
		this.myphotosPath = myphotosPath;
		this.mylinksPath = mylinksPath;
		this.mymusicPath = mymusicPath;
		this.myvideosPath = myvideosPath;
		this.emailServer = emailServer;
		this.emailUsername = emailUsername;
		this.emailPassword = emailPassword;
		this.emailAcctType = emailAcctType;
		this.emailPortOutbound = emailPortOutbound;
		this.emailPortInbound = emailPortInbound;
		this.password = password;
		this.homepage = homepage;
		this.activeStatus = activeStatus;
		this.password2 = password2;
		this.pictureFilepath = pictureFilepath;
		this.termsAndConditionsFlag = termsAndConditionsFlag;
		this.userCompanyName = userCompanyName;
		this.userAddress = userAddress;
		this.userSuite = userSuite;
		this.userCity = userCity;
		this.userState = userState;
		this.userCountry = userCountry;
		this.userPostalCode = userPostalCode;
		this.favorites = favorites;
		this.emailAccounts = emailAccounts;
		this.socialMediaAccounts = socialMediaAccounts;
		this.createDate = createDate;
		this.createUser = createUser;
		this.apiKey = apiKey;
		this.apiSecret = apiSecret;
		this.version = version;
		this.cloudName = cloudName;
	}

	@Id

	@Column(name = "ID", unique = true, nullable = false, length = 30)
	public String getId() {
		return this.id;
	}

	public void setId(String id) {
		this.id = id;
	}

	@Column(name = "USERNAME", nullable = false, length = 128)
	public String getUsername() {
		return this.username;
	}

	public void setUsername(String username) {
		this.username = username;
	}

	@Column(name = "FIRST_NAME", length = 32)
	public String getFirstName() {
		return this.firstName;
	}

	public void setFirstName(String firstName) {
		this.firstName = firstName;
	}

	@Column(name = "MIDDLE_INITIAL", length = 1)
	public Character getMiddleInitial() {
		return this.middleInitial;
	}

	public void setMiddleInitial(Character middleInitial) {
		this.middleInitial = middleInitial;
	}

	@Column(name = "LAST_NAME", length = 32)
	public String getLastName() {
		return this.lastName;
	}

	public void setLastName(String lastName) {
		this.lastName = lastName;
	}

	@Column(name = "EMAIL", length = 128)
	public String getEmail() {
		return this.email;
	}

	public void setEmail(String email) {
		this.email = email;
	}

	@Column(name = "OFFICE_PHONE", length = 16)
	public String getOfficePhone() {
		return this.officePhone;
	}

	public void setOfficePhone(String officePhone) {
		this.officePhone = officePhone;
	}

	@Column(name = "MOBILE_PHONE", length = 16)
	public String getMobilePhone() {
		return this.mobilePhone;
	}

	public void setMobilePhone(String mobilePhone) {
		this.mobilePhone = mobilePhone;
	}

	@Column(name = "ACCOUNT_STATUS_CODE")
	public Integer getAccountStatusCode() {
		return this.accountStatusCode;
	}

	public void setAccountStatusCode(Integer accountStatusCode) {
		this.accountStatusCode = accountStatusCode;
	}

	@Column(name = "USER_GROUP_ID")
	public Integer getUserGroupId() {
		return this.userGroupId;
	}

	public void setUserGroupId(Integer userGroupId) {
		this.userGroupId = userGroupId;
	}

	@Column(name = "SECURITY_CONTEXT_ID")
	public Integer getSecurityContextId() {
		return this.securityContextId;
	}

	public void setSecurityContextId(Integer securityContextId) {
		this.securityContextId = securityContextId;
	}

	@Column(name = "USER_DESCR", length = 64)
	public String getUserDescr() {
		return this.userDescr;
	}

	public void setUserDescr(String userDescr) {
		this.userDescr = userDescr;
	}

	@Column(name = "LAST_UPDATE_USER")
	public Integer getLastUpdateUser() {
		return this.lastUpdateUser;
	}

	public void setLastUpdateUser(Integer lastUpdateUser) {
		this.lastUpdateUser = lastUpdateUser;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "LAST_UPDATE_DATE", length = 19)
	public Date getLastUpdateDate() {
		return this.lastUpdateDate;
	}

	public void setLastUpdateDate(Date lastUpdateDate) {
		this.lastUpdateDate = lastUpdateDate;
	}

	@Column(name = "LAST_WORKSPACE_ID")
	public Integer getLastWorkspaceId() {
		return this.lastWorkspaceId;
	}

	public void setLastWorkspaceId(Integer lastWorkspaceId) {
		this.lastWorkspaceId = lastWorkspaceId;
	}

	@Column(name = "LAST_PROJECT_ID")
	public Integer getLastProjectId() {
		return this.lastProjectId;
	}

	public void setLastProjectId(Integer lastProjectId) {
		this.lastProjectId = lastProjectId;
	}

	@Column(name = "webmail_url")
	public String getWebmailUrl() {
		return this.webmailUrl;
	}

	public void setWebmailUrl(String webmailUrl) {
		this.webmailUrl = webmailUrl;
	}

	@Column(name = "CUSTOMER_ID")
	public Integer getCustomerId() {
		return this.customerId;
	}

	public void setCustomerId(Integer customerId) {
		this.customerId = customerId;
	}

	@Column(name = "MEMBERSHIP_TYPE", precision = 10, scale = 0)
	public Long getMembershipType() {
		return this.membershipType;
	}

	public void setMembershipType(Long membershipType) {
		this.membershipType = membershipType;
	}

	@Column(name = "MYDOCUMENTS_PATH", length = 2048)
	public String getMydocumentsPath() {
		return this.mydocumentsPath;
	}

	public void setMydocumentsPath(String mydocumentsPath) {
		this.mydocumentsPath = mydocumentsPath;
	}

	@Column(name = "MYPHOTOS_PATH", length = 2048)
	public String getMyphotosPath() {
		return this.myphotosPath;
	}

	public void setMyphotosPath(String myphotosPath) {
		this.myphotosPath = myphotosPath;
	}

	@Column(name = "MYLINKS_PATH", length = 2048)
	public String getMylinksPath() {
		return this.mylinksPath;
	}

	public void setMylinksPath(String mylinksPath) {
		this.mylinksPath = mylinksPath;
	}

	@Column(name = "MYMUSIC_PATH", length = 2048)
	public String getMymusicPath() {
		return this.mymusicPath;
	}

	public void setMymusicPath(String mymusicPath) {
		this.mymusicPath = mymusicPath;
	}

	@Column(name = "MYVIDEOS_PATH", length = 2048)
	public String getMyvideosPath() {
		return this.myvideosPath;
	}

	public void setMyvideosPath(String myvideosPath) {
		this.myvideosPath = myvideosPath;
	}

	@Column(name = "EMAIL_SERVER", length = 64)
	public String getEmailServer() {
		return this.emailServer;
	}

	public void setEmailServer(String emailServer) {
		this.emailServer = emailServer;
	}

	@Column(name = "EMAIL_USERNAME", length = 32)
	public String getEmailUsername() {
		return this.emailUsername;
	}

	public void setEmailUsername(String emailUsername) {
		this.emailUsername = emailUsername;
	}

	@Column(name = "EMAIL_PASSWORD", length = 32)
	public String getEmailPassword() {
		return this.emailPassword;
	}

	public void setEmailPassword(String emailPassword) {
		this.emailPassword = emailPassword;
	}

	@Column(name = "EMAIL_ACCT_TYPE")
	public Integer getEmailAcctType() {
		return this.emailAcctType;
	}

	public void setEmailAcctType(Integer emailAcctType) {
		this.emailAcctType = emailAcctType;
	}

	@Column(name = "EMAIL_PORT_OUTBOUND")
	public Integer getEmailPortOutbound() {
		return this.emailPortOutbound;
	}

	public void setEmailPortOutbound(Integer emailPortOutbound) {
		this.emailPortOutbound = emailPortOutbound;
	}

	@Column(name = "EMAIL_PORT_INBOUND")
	public Integer getEmailPortInbound() {
		return this.emailPortInbound;
	}

	public void setEmailPortInbound(Integer emailPortInbound) {
		this.emailPortInbound = emailPortInbound;
	}

	@Column(name = "PASSWORD", length = 128)
	public String getPassword() {
		return this.password;
	}

	public void setPassword(String password) {
		this.password = password;
	}

	@Column(name = "HOMEPAGE", length = 128)
	public String getHomepage() {
		return this.homepage;
	}

	public void setHomepage(String homepage) {
		this.homepage = homepage;
	}

	@Column(name = "ACTIVE_STATUS", length = 8)
	public String getActiveStatus() {
		return this.activeStatus;
	}

	public void setActiveStatus(String activeStatus) {
		this.activeStatus = activeStatus;
	}

	@Column(name = "PASSWORD2", length = 128)
	public String getPassword2() {
		return this.password2;
	}

	public void setPassword2(String password2) {
		this.password2 = password2;
	}

	@Column(name = "PICTURE_FILEPATH")
	public String getPictureFilepath() {
		return this.pictureFilepath;
	}

	public void setPictureFilepath(String pictureFilepath) {
		this.pictureFilepath = pictureFilepath;
	}

	@Column(name = "TERMS_AND_CONDITIONS_FLAG")
	public Boolean getTermsAndConditionsFlag() {
		return this.termsAndConditionsFlag;
	}

	public void setTermsAndConditionsFlag(Boolean termsAndConditionsFlag) {
		this.termsAndConditionsFlag = termsAndConditionsFlag;
	}

	@Column(name = "USER_COMPANY_NAME", length = 64)
	public String getUserCompanyName() {
		return this.userCompanyName;
	}

	public void setUserCompanyName(String userCompanyName) {
		this.userCompanyName = userCompanyName;
	}

	@Column(name = "USER_ADDRESS", length = 32)
	public String getUserAddress() {
		return this.userAddress;
	}

	public void setUserAddress(String userAddress) {
		this.userAddress = userAddress;
	}

	@Column(name = "USER_SUITE", length = 8)
	public String getUserSuite() {
		return this.userSuite;
	}

	public void setUserSuite(String userSuite) {
		this.userSuite = userSuite;
	}

	@Column(name = "USER_CITY", length = 32)
	public String getUserCity() {
		return this.userCity;
	}

	public void setUserCity(String userCity) {
		this.userCity = userCity;
	}

	@Column(name = "USER_STATE", length = 32)
	public String getUserState() {
		return this.userState;
	}

	public void setUserState(String userState) {
		this.userState = userState;
	}

	@Column(name = "USER_COUNTRY", length = 32)
	public String getUserCountry() {
		return this.userCountry;
	}

	public void setUserCountry(String userCountry) {
		this.userCountry = userCountry;
	}

	@Column(name = "USER_POSTAL_CODE", length = 16)
	public String getUserPostalCode() {
		return this.userPostalCode;
	}

	public void setUserPostalCode(String userPostalCode) {
		this.userPostalCode = userPostalCode;
	}

	@Column(name = "FAVORITES", length = 65535)
	public String getFavorites() {
		return this.favorites;
	}

	public void setFavorites(String favorites) {
		this.favorites = favorites;
	}

	@Column(name = "EMAIL_ACCOUNTS", length = 65535)
	public String getEmailAccounts() {
		return this.emailAccounts;
	}

	public void setEmailAccounts(String emailAccounts) {
		this.emailAccounts = emailAccounts;
	}

	@Column(name = "SOCIAL_MEDIA_ACCOUNTS", length = 65535)
	public String getSocialMediaAccounts() {
		return this.socialMediaAccounts;
	}

	public void setSocialMediaAccounts(String socialMediaAccounts) {
		this.socialMediaAccounts = socialMediaAccounts;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "CREATE_DATE", length = 19)
	public Date getCreateDate() {
		return this.createDate;
	}

	public void setCreateDate(Date createDate) {
		this.createDate = createDate;
	}

	@Column(name = "CREATE_USER")
	public Integer getCreateUser() {
		return this.createUser;
	}

	public void setCreateUser(Integer createUser) {
		this.createUser = createUser;
	}

	@Column(name = "API_KEY", length = 32)
	public String getApiKey() {
		return this.apiKey;
	}

	public void setApiKey(String apiKey) {
		this.apiKey = apiKey;
	}

	@Column(name = "API_SECRET", length = 32)
	public String getApiSecret() {
		return this.apiSecret;
	}

	public void setApiSecret(String apiSecret) {
		this.apiSecret = apiSecret;
	}

	@Column(name = "VERSION", length = 32)
	public String getVersion() {
		return this.version;
	}

	public void setVersion(String version) {
		this.version = version;
	}

	@Column(name = "CLOUD_NAME", length = 64)
	public String getCloudName() {
		return this.cloudName;
	}

	public void setCloudName(String cloudName) {
		this.cloudName = cloudName;
	}

}
